name: virallc
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - biopython=1.86=py314h6c2aa35_1
  - blast=2.16.0=hb260f6e_5
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.6=hfe05a68_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - curl=8.18.0=h6430ca7_0
  - entrez-direct=22.4=hd5f1084_0
  - gawk=5.3.1=hefee741_0
  - gettext=0.21.0=hbdbcc25_2
  - icu=73.1=h313beb8_0
  - jansson=2.14=h80987f9_1
  - libblas=3.11.0=5_h51639a9_openblas
  - libbrotlicommon=1.2.0=hbd7815e_0
  - libbrotlidec=1.2.0=h1e834b2_0
  - libbrotlienc=1.2.0=h5439a07_0
  - libcblas=3.11.0=5_hb0561ab_openblas
  - libcurl=8.18.0=hd4c70c6_0
  - libcxx=21.1.8=hb4ce287_0
  - libev=4.33=h1a28f6b_1
  - libexpat=2.7.4=hf6b4638_0
  - libffi=3.5.2=hcf2aa1b_0
  - libgcc=15.2.0=hcbb3090_17
  - libgfortran=15.2.0=h07b0088_17
  - libgfortran5=15.2.0=hdae7583_17
  - libiconv=1.16=h80987f9_3
  - libidn2=2.3.8=h9681e36_0
  - libkrb5=1.22.1=ha46c28b_0
  - liblapack=3.11.0=5_hd9741b5_openblas
  - libmpdec=4.0.0=h84a0fba_1
  - libnghttp2=1.67.1=h8189af8_0
  - libopenblas=0.3.30=openmp_ha158390_4
  - libsqlite=3.51.2=h1b79a29_0
  - libssh2=1.11.1=h3e2b118_0
  - libunistring=1.3=h1799b2a_0
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - lmdb=0.9.31=h79febb2_0
  - mafft=7.526=h99b78c6_0
  - ncbi-vdb=3.3.0=h4675bf2_0
  - ncurses=6.5=hee39554_0
  - networkx=3.6.1=pyhcf101f3_0
  - nextclade=3.18.1=h4f1019d_0
  - numpy=2.4.2=py314hae46ccb_1
  - openssl=3.6.1=hd24854e_1
  - pandas=3.0.0=py314h5e21a50_0
  - pcre2=10.46=h1dacb4a_0
  - perl=5.32.1=7_h4614cfb_perl5
  - perl-archive-tar=3.04=pl5321hdfd78af_0
  - perl-carp=1.38=pl5321hdfd78af_4
  - perl-common-sense=3.75=pl5321hdfd78af_0
  - perl-compress-raw-bzip2=2.214=pl5321h2ddc596_0
  - perl-compress-raw-zlib=2.214=pl5321ha1c2b25_0
  - perl-encode=3.21=pl5321h5505292_1
  - perl-exporter=5.72=pl5321hdfd78af_2
  - perl-exporter-tiny=1.002002=pl5321hdfd78af_0
  - perl-extutils-makemaker=7.3506=pl5340hca03da5_0
  - perl-io-compress=2.216=pl5321haef7865_0
  - perl-io-zlib=1.15=pl5321hdfd78af_1
  - perl-json=4.10=pl5321hdfd78af_1
  - perl-json-xs=4.04=pl5321h4675bf2_0
  - perl-list-moreutils=0.430=pl5321hdfd78af_0
  - perl-list-moreutils-xs=0.430=pl5321hbdacb55_5
  - perl-parent=0.236=pl5321hdfd78af_2
  - perl-pathtools=3.75=pl5321hc71e825_2
  - perl-scalar-list-utils=1.70=pl5321h44e845a_0
  - perl-storable=3.15=pl5321hc71e825_2
  - perl-types-serialiser=1.01=pl5321hdfd78af_0
  - pip=26.0.1=pyh145f28c_0
  - python=3.14.2=h1858270_101_cp314
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.14=8_cp314
  - readline=8.3=h0b18652_0
  - rpsbproc=0.5.1=hf8bb5b5_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.2=h85ec8f2_0
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025c=hc9c84f9_1
  - wget=1.25.0=hbc1a67d_2
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=hbf9d68e_6
  - pip:
      - build==1.4.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - colorama==0.4.6
      - contourpy==1.3.3
      - cycler==0.12.1
      - docutils==0.22.4
      - fonttools==4.61.1
      - fsspec==2026.2.0
      - gitdir==1.2.7
      - id==1.6.1
      - idna==3.11
      - jaraco-classes==3.4.0
      - jaraco-context==6.1.0
      - jaraco-functools==4.4.0
      - keyring==25.7.0
      - kiwisolver==1.4.9
      - markdown-it-py==4.0.0
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - more-itertools==10.8.0
      - nh3==0.3.3
      - packaging==26.0
      - pillow==12.1.1
      - pygments==2.19.2
      - pyparsing==3.3.2
      - pyproject-hooks==1.2.0
      - readme-renderer==44.0
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rfc3986==2.0.0
      - rich==14.3.2
      - setuptools==82.0.0
      - snipit==1.7
      - toml==0.10.2
      - twine==6.2.0
      - urllib3==2.6.3
      - virallc==1.0.14
prefix: /Users/cchaguza/anaconda3/envs/virallc
