name: py3
channels:
  - conda-forge
  - anaconda
  - defaults
  - bioconda
dependencies:
  - blas=2.131=openblas
  - blas-devel=3.9.0=31_h11c0a38_openblas
  - brotli=1.1.0=hd74edd7_2
  - brotli-bin=1.1.0=hd74edd7_2
  - bzip2=1.0.8=h99b78c6_7
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - contourpy=1.3.1=py313h0ebd0e5_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - fonttools=4.56.0=py313ha9b7d5b_0
  - freetype=2.12.1=hadb7bae_2
  - gawk=5.3.1=h8a92848_0
  - gmp=6.3.0=h7bae524_2
  - icu=75.1=hfee45f7_0
  - ipykernel=6.29.5=py313hca03da5_1
  - jedi=0.19.2=py313hca03da5_0
  - joblib=1.4.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=py313hca03da5_0
  - jupyter_core=5.7.2=py313hca03da5_0
  - kiwisolver=1.4.8=py313h313beb8_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=h9a09cb3_0
  - libabseil=20240722.0=cxx17_h07bc746_4
  - libasprintf=0.25.1=h493aca8_0
  - libblas=3.9.0=31_h10e41b3_openblas
  - libbrotlicommon=1.1.0=hd74edd7_2
  - libbrotlidec=1.1.0=hd74edd7_2
  - libbrotlienc=1.1.0=hd74edd7_2
  - libcblas=3.9.0=31_hb3479ef_openblas
  - libcxx=19.1.7=ha82da77_0
  - libdeflate=1.23=hec38601_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libexpat=2.6.4=h286801f_0
  - libffi=3.4.2=h3422bc3_5
  - libgettextpo=0.25.1=h493aca8_0
  - libgfortran=5.0.0=13_2_0_hd922786_3
  - libgfortran5=13.2.0=hf226fd6_3
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libjpeg-turbo=3.0.0=hb547adb_1
  - liblapack=3.9.0=31_hc9a63f6_openblas
  - liblapacke=3.9.0=31_hbb7bcf8_openblas
  - liblzma=5.6.4=h39f12f2_0
  - libmpdec=4.0.0=h99b78c6_0
  - libopenblas=0.3.29=openmp_hf332438_0
  - libpng=1.6.47=h3783ad8_0
  - libprotobuf=5.28.3=h3bd63a1_1
  - libsodium=1.0.18=h1a28f6b_0
  - libsqlite=3.49.1=h3f77e49_1
  - libtiff=4.7.0=h551f018_3
  - libwebp-base=1.5.0=h2471fea_0
  - libxcb=1.17.0=hdb1d25a_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=19.1.7=hdb05f8b_0
  - lz4-c=1.10.0=h286801f_1
  - mafft=7.526=h99b78c6_0
  - matplotlib=3.10.1=py313h39782a4_0
  - matplotlib-base=3.10.1=py313haaf02c0_0
  - mpfr=4.2.1=hb693164_3
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql=9.0.1=h44b9a77_4
  - mysql-client=9.0.1=ha8be5b7_4
  - mysql-common=9.0.1=hd7719f6_4
  - mysql-devel=9.0.1=hd7719f6_4
  - mysql-libs=9.0.1=ha8be5b7_4
  - mysql-server=9.0.1=h4a26de9_4
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=py313hca03da5_0
  - nextclade=3.18.0=h4f1019d_0
  - openblas=0.3.29=openmp_hea878ba_0
  - openjpeg=2.5.3=h8a3d83b_0
  - openssl=3.6.0=h5503f6c_0
  - packaging=24.2=pyhd8ed1ab_2
  - parso=0.8.4=py313hca03da5_0
  - pillow=11.1.0=py313hb37fac4_0
  - pip=25.0.1=pyh145f28c_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyparsing=3.2.1=pyhd8ed1ab_0
  - python=3.13.2=h81fe080_101_cp313
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.13=5_cp313
  - qhull=2020.2=h420ef59_5
  - readline=8.2=h1d1bf99_2
  - scikit-learn=1.6.1=py313h313beb8_0
  - scipy=1.15.1=py313h858dd5b_0
  - seaborn=0.12.2=py313hca03da5_0
  - six=1.17.0=pyhd8ed1ab_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=h5083fa2_1
  - tornado=6.4.2=py313h90d716c_0
  - traitlets=5.14.3=py313hca03da5_0
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - zeromq=4.3.5=h313beb8_0
  - zstd=1.5.7=h6491c7d_1
  - pip:
      - appnope==0.1.4
      - argparse==1.4.0
      - asttokens==3.0.0
      - biopython==1.86
      - build==1.3.0
      - comm==0.2.2
      - debugpy==1.8.12
      - decorator==5.2.1
      - executing==2.2.0
      - fsspec==2025.10.0
      - imbalanced-learn==0.13.0
      - imblearn==0.0
      - ipython==9.0.0
      - ipython-pygments-lexers==1.1.1
      - matplotlib-inline==0.1.7
      - numpy==2.3.5
      - pandas==2.3.3
      - pathlib==1.0.1
      - pexpect==4.9.0
      - platformdirs==4.3.6
      - prompt-toolkit==3.0.50
      - psutil==7.0.0
      - pure-eval==0.2.3
      - pygments==2.19.1
      - pyproject-hooks==1.2.0
      - pytz==2025.2
      - pyzmq==26.2.1
      - setuptools==80.9.0
      - sklearn-compat==0.1.3
      - stack-data==0.6.3
      - toml==0.10.2
      - tzdata==2025.2
      - virallc==1.0.0
      - wcwidth==0.2.13
prefix: /Users/cchaguza/anaconda3/envs/py3
